services:
  backend-api:
    build:
      context: ./backend/CloudPlatform.Api
    ports:
      - "5140:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend-portal:
    build:
      context: ./frontend 
    ports:
      - "5173:80" 
    depends_on:
      - backend-api